#https://github.com/traefik/traefik/blob/master/traefik.sample.yml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  insecure: true

providers:
  docker:
    exposedbydefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true
tls:
  certificate:
    - certFile: /etc/traefik/server.crt
    - keyFile: /etc/traefik/server.key
    
