version: "3.8"
services:
    srs:
        image: ossrs/srs:aarch64
        volumes: 
            - ./git:/root/git
        #command: tail -f /dev/null
        command: >
            bash -c "apt update && 
            apt install -y git &&
            cd ~/git &&
            rm -rf srs &&  
            git clone https://gitee.com/winlinvip/srs.oschina.git srs &&
            cd srs/trunk &&
            git remote set-url origin https://github.com/ossrs/srs.git &&
            git pull &&
            ./configure &&
            make"
