version: "3.8"
services: 
    #docker-compose up --build
    #http://cyberplayer.bcelive.com/demo/new/index.html
    brpc-media-server:
        image: 76527413/brpc-media-server:latest
        build: .
        ports: 
            - 8079:8079
        entrypoint: tail -f /dev/null