version: "3.8"
services:
    traefik:
        image: traefik:v2.5
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./conf:/etc/traefik
        command: 
            - --certificatesresolvers.default.acme.tlschallenge=true
            #- --certificatesresolvers.http.acme.httpchallenge.entrypoint=web
            # - --certificatesresolvers.tls.acme.tlschallenge=true
            # - --certificatesresolvers.tls.acme.tlschallenge.entrypoint=websecure
    whoami:
        image: traefik/whoami
        labels:
            - traefik.enable=true
            - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
            - traefik.http.routers.whoami.entrypoints=web,websecure
            - traefik.http.routers.whoami.tls.certresolver=default
            #- traefik.http.routers.whoami.http.certresolver=default
